 <center>
    
 # Segundo Parcial - Optimización 2020
## FaMAFyC
### Emanuel Matar

$OP-P3-E1$ Implementar los siguientes algoritmos para resolver sistemas no lineales: método de Newton,
método de Newton estacionario, método de Newton estacionario con recomienzos cada m iteraciones y el método de Broyden. 
Los datos de entrada de ambos algoritmos deberán ser una aproximación inicial, una tolerancia para el criterio de parada, una cantidad máxima de iteraciones y el parámetro m para el método de Newton estacionario con recomienzos. 
La función y
la matriz jacobiana, cuando corresponda, deberán escribirse en otra subrutina o función independiente.
La salida deberá incluir: el valor del minimizador, el valor de mínimo, el número de Iteraciones y el error en $x$, en aquellos casos que se conozca la solución.

**Observación** en cada una de las implementaciones aparece una variable `e_[nombre del método]`que respresenta el error entre la solución conocida del problema y la obtenida en la implementación del correspondiente algoritmo. En caso de que no se conozca la solución, cada algoritmo imprime un mensaje y devuelve la norma del vector resultante.

### Método de Newton

In [1]:
format long

In [2]:
function [x0,y,e_newton] = newton(F,JF,x0,tol,maxit,y)
f=F(x0);
Jf=JF(x0);
i=1;
while(norm(f)>tol && i<maxit)
    s=inv(Jf)*f'; 
    s=(-1)*s';
    x=x0;
    x0=x0.+s;
    f=F(x0); 
    Jf=JF(x0);
    i=i+1;
    endwhile
    if (nargin == 6)
    e_newton=norm(x0-y);
    else
    display("No hay punto óptimo de referencia para comparar")
    norma=norm(x0)
    end
endfunction 

### Método de Newton Estacionario

In [3]:
function [x0,y,e_newton_estacionario]=newtonestacionario(F,JF,x0,tol,maxit,y)
f=F(x0);
Jf=JF(x0);
A=inv(Jf);
i=1;
while (norm(f)>tol && i<maxit)
    s=A*f';
    s=-s';
    x0=x0.+s;
    f=F(x0);
    i=i+1;
    endwhile
    if (nargin == 6)
    e_newton_estacionario=norm(x0-y);
    else
    display("No hay punto óptimo de referencia para comparar")
    norma=norm(x0)
    end
endfunction 
%La diferencia entre Newton estacionario y el comun, es que este calcula una sola vez la Jacobiana en el primer x0

### Método de Newton Estacionario con refresh

In [4]:
function [x0,y,e_estacionario_refresh]=newtonconrefresh(F,JF,x0,tol,maxit,m,y)
f=F(x0);
Jf=JF(x0);
A=inv(Jf);
i=1;
k=0;
while (norm(f)>tol && i<maxit)
    s=A*f';
    s=-s';
    x0=x0.+s;
    f=F(x0);
    i=i+1;
    k=k+1;
        if k==m
        Jf=JF(x0);
        A=inv(Jf);
        k=0;
        endif
    endwhile
    if (nargin == 7)
    e_estacionario_refresh=norm(x0-y);
    else
    display("No hay punto óptimo de referencia para comparar")
    norma=norm(x0)
    end
endfunction 
%En este newton se actualiza la Jacobiana cada m iteracciones.

### Método de Broyden

In [5]:
function [x0,y,e_broyden]=Broyden(F,JF,x0,tol,maxit,y)
f=F(x0);
A=JF(x0);
k=1;
while (norm(f)>tol && k<maxit)
   s=inv(A)*(f');
   s=-s';
   x=x0;
   x0=x0+s;
   f=F(x0);
   f1=F(x);
   t=f-f1;
   u=A*(s');
   u=u';
   t=(t-u)'*(s);
   v=norm(s)^2;
   A=A.+(t/v);
   k=k+1;
   endwhile
   if (nargin == 6)
    e_broyden=norm(x0-y);
    else
    display("No hay punto óptimo de referencia para comparar")
    norma=norm(x0)
    end
   endfunction 

$OP-P3-E2$ Aplicar todas las implementaciones anteriores para resolver F(x) = 0, para las siguientes funciones y comparar los resultados obtenidos con los diferentes métodos.


 $(a)$ $F(x) = 
\Bigg(
    \begin{matrix}
        (x_1+3)(x_2^3-7)+18 \\
        sen(x_2e^{x_1}-1) 
    \end{matrix}
\Bigg)$

$x_* = (0,1)$, $x_0 = (-0.5 ; 1.4)$


In [6]:
function F=Fa(x)
F=[(x(1)+3)*(x(2)^(3)-7)+18, sin(x(2)*exp(x(1))-1)];
endfunction

In [7]:
function JF=JFa(x)
JF=[x(2)^(3)-7 (x(1)+3)*(3*x(2)^(2));cos(x(2)*exp(x(1))-1)*x(2)*exp(x(1)), cos(x(2)*exp(x(1))-1)*exp(x(1))];
endfunction

In [8]:
ya=[0,1]
x0a=[-0.5,1.4]

ya =

   0   1

x0a =

  -5.000000000000000e-01   1.400000000000000e+00



Procedemos a aplicar los algoritmos programados supra

`Newton`

In [9]:
[xmina,ya,e_newton] = newton(@Fa,@JFa,x0a,1e-4,100,ya)

xmina =

  -1.779077709717497e-08   1.000000005551385e+00

ya =

   0   1

e_newton =    1.863678155089833e-08


`Newton estacionario`

In [10]:
[xmina,ya,e_newton_estacionario]=newtonestacionario(@Fa,@JFa,x0a,1e-4,100,ya)

xmina =

  -8.030298965463242e-06   1.000003955759192e+00

ya =

   0   1

e_newton_estacionario =    8.951744648933499e-06


`Newton Estacionario con refresh`

In [11]:
[xmina,ya,e_estacionario_refresh]=newtonconrefresh(@Fa,@JFa,x0a,1e-4,100,5,ya)

xmina =

  -8.030298965463242e-06   1.000003955759192e+00

ya =

   0   1

e_estacionario_refresh =    8.951744648933499e-06


`Méotodo de Broyden`

In [12]:
[xmina,ya,e_broyden]=Broyden(@Fa,@JFa,x0a,1e-4,100,ya)

xmina =

  -1.327508959181220e-07   1.000000045338361e+00

ya =

   0   1

e_broyden =    1.402796041880864e-07


Para este ejercicio vemos, al comparar la norma de los errores, que el método más preciso fue el de `Newton`

$(b)$ $F(x) =
\begin{pmatrix}
    x_1 + x_2 - 3 \\
    x_1^2 + x_2^2 - 9
\end{pmatrix}$

$x_* = (0,3)$, $x_0 = (1,5)$

In [13]:
yb=[0,3]
x0b=[1, 5]

yb =

   0   3

x0b =

   1   5



In [14]:
function F=Fb(x)
F=[x(1)+x(2)-3, x(1)^2+x(2)^2-9];
endfunction

In [15]:
function JF=JFb(x)
JF=[1,1; 2*x(1), 2*x(2)];
endfunction

`Newton`

In [16]:
[xminb,yb,e_newton] = newton(@Fb,@JFb,x0b,1e-4,100,yb)

xminb =

  -2.342597337527761e-06   3.000002342597337e+00

yb =

   0   3

e_newton =    3.312932925852904e-06


`Newton estacionario`

In [17]:
[xminb,yb,e_newton_estacionario]=newtonestacionario(@Fb,@JFb,x0b,1e-4,100,yb)

xminb =

  -1.322134777759221e-05   3.000013221347777e+00

yb =

   0   3

e_newton_estacionario =    1.869780933984377e-05


`Newton Estacionario con refresh`

In [18]:
[xminb,yb,e_estacionario_refresh]=newtonconrefresh(@Fb,@JFb,x0b,1e-4,100,5,yb)

xminb =

  -2.390621430127093e-07   3.000000239062143e+00

yb =

   0   3

e_estacionario_refresh =    3.380849248686507e-07


`Méotodo de Broyden`

In [19]:
[xminb,yb,e_broyden]=Broyden(@Fb,@JFb,x0b,1e-4,100,yb)

xminb =

  -1.332561801562241e-06   3.000001332561801e+00

yb =

   0   3

e_broyden =    1.884526972318311e-06


En este ejercicio, observamos que el algoritmo que mejor converge es el del método de `Newton Estacionario con refresh` al actualizar la matriz jacobiana cada 5 iteraciones.

$(c)$ $F(x) = 
\begin{pmatrix}
    x_1^2 + x_2^2 - 2 \\
    e^{x_1-1} + x_2^3 -2
\end{pmatrix}$

$x_* = (1,1)$, $ x_0 = (1.5,2)$

In [20]:
yc=[1,1]
x0c=[1.5, 2]

yc =

   1   1

x0c =

   1.500000000000000   2.000000000000000



In [21]:
function F=Fc(x)
F=[x(1)^2+x(2)^2-2, exp(x(1)-1)+(x(2)^3-2)];
endfunction

In [22]:
function JF=JFc(x)
JF=[2*x(1),2*x(2); exp(x(1)-1), 3*(x(2)^2)];
endfunction

`Newton`

In [23]:
[xminc,yc,e_newton] = newton(@Fc,@JFc,x0c,1e-4,100,yc)

xminc =

   9.999998280535310e-01   1.000000357219383e+00

yc =

   1   1

e_newton =    3.964483263074689e-07


`Newton estacionario`

In [24]:
[xminc,yc,e_newton_estacionario]=newtonestacionario(@Fc,@JFc,x0c,1e-4,100,yc)

xminc =

   9.999609873087860e-01   1.000045651863008e+00

yc =

   1   1

e_newton_estacionario =    6.005066753855572e-05


`Newton Estacionario con refresh`

In [25]:
[xminc,yc,e_estacionario_refresh]=newtonconrefresh(@Fc,@JFc,x0c,1e-4,100,5,yc)

xminc =

   9.999999983413719e-01   1.000000003060691e+00

yc =

   1   1

e_estacionario_refresh =    3.481217921557920e-09


`Méotodo de Broyden`

In [26]:
[xminc,yc,e_broyden]=Broyden(@Fc,@JFc,x0c,1e-4,100,yc)

xminc =

   9.999981826950856e-01   1.000000003888380e+00

yc =

   1   1

e_broyden =    1.817309074305518e-06


En este ejercicio, observamos que el algoritmo que mejor converge es el del método de `Newton Estacionario con refresh` al actualizar la matriz jacobiana cada 5 iteraciones.

$(d)$ $F(x) =
\begin{pmatrix}
    10(x_2-x_1^2) \\
    1-x_1
\end{pmatrix}$

$x_* = (1,1)$, $x_0 = (-1.2,1)$

In [27]:
yd=[1,1]
x0d=[-1.2, 1]

yd =

   1   1

x0d =

  -1.200000000000000   1.000000000000000



In [28]:
function F=Fd(x)
F=[10*(x(2)-(x(1)^2)), 1-x(1)];
endfunction

In [29]:
function JF=JFd(x)
JF=[20*x(1),10; -1, 0];
endfunction

`Newton`

In [30]:
[xmind,yd,e_newton] = newton(@Fd,@JFd,x0d,1e-4,100,yd)

xmind =

   1.000000000000000   1.000000000000001

yd =

   1   1

e_newton =    8.881784197001252e-16


`Newton estacionario`

In [31]:
[xmind,yd,e_newton_estacionario]=newtonestacionario(@Fd,@JFd,x0d,1e-4,100,yd)

xmind =

   1.000000000000000e+00   9.999999999999991e-01

yd =

   1   1

e_newton_estacionario =    8.881784197001252e-16


`Newton Estacionario con refresh`

In [32]:
[xmind,yd,e_estacionario_refresh]=newtonconrefresh(@Fd,@JFd,x0d,1e-4,100,5,yd)

xmind =

   1.000000000000000e+00   9.999999999999991e-01

yd =

   1   1

e_estacionario_refresh =    8.881784197001252e-16


`Méotodo de Broyden`

In [33]:
[xmind,yd,e_broyden]=Broyden(@Fd,@JFd,x0d,1e-4,100,yd)

xmind =

   1   1

yd =

   1   1

e_broyden = 0


En este inciso vemos que el método que converge de un modo *exacto*, es decir, sin errores, es el `Méotodo de Broyden` mientras que los demás dan un error que puede considerarse un *cero de máquina* y todos arrojan el mismo resultado.

$(e)$ $F$ dada por:

$f_1(x) = (3-2x_1)x_1-2x_2+1$

$f_i(x) = (3-2x_i)x_i-x_{i-1}-2x_{i+1}+1$, para $i = 2:9$

$f_{10}(x) = (3-2x_{10})x_{10}-x_9+1$

$x_0 = (-1,-1,...,-1)$

In [34]:
x0e=-ones(1,10)


x0e =

  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1



In [35]:
function F=Fe(x)
F=zeros(1,10);
F(1)=(3-2*x(1))*x(1)-2*x(2)+1;
for i=2:9
F(i)=(3-2*x(i))*x(i)-x(i-1)-2*x(i+1)+1;
end
F(10)=(3-2*x(10))*x(10)-x(9)+1;

endfunction 

In [36]:
function JF=JFe(x)
JF=3*eye(10);
for i=1:9
    JF(i,i+1)=-2;
end
for j=2:10
    JF(j,j-1)=-1;
end
for k=1:10
    JF(k,k)=JF(k,k)-4*x(k);
end
endfunction 

`Newton`

In [37]:
xmine = newton(@Fe,@JFe,x0e,1e-4,100)

No hay punto óptimo de referencia para comparar
norma =  2.054545341032465
xmine =

 Columns 1 through 3:

  -5.707248899422406e-01  -6.818091012988381e-01  -7.022117660766358e-01

 Columns 4 through 6:

  -7.055123997532535e-01  -7.049085660379604e-01  -7.015005403045774e-01

 Columns 7 through 9:

  -6.918963810592651e-01  -6.658091347098586e-01  -5.960545365666399e-01

 Column 10:

  -4.164305296849135e-01



`Newton estacionario`

In [38]:
xmine=newtonestacionario(@Fe,@JFe,x0e,1e-4,100)

No hay punto óptimo de referencia para comparar
norma =  2.054543219961177
xmine =

 Columns 1 through 3:

  -5.707240087847397e-01  -6.818084915233514e-01  -7.022115489285672e-01

 Columns 4 through 6:

  -7.055124651257466e-01  -7.049088512176073e-01  -7.015008733966193e-01

 Columns 7 through 9:

  -6.918962343519373e-01  -6.658075109157250e-01  -5.960510985774672e-01

 Column 10:

  -4.164292433974416e-01



`Newton Estacionario con refresh`

In [39]:
xmine=newtonconrefresh(@Fe,@JFe,x0e,1e-6,100,4)

No hay punto óptimo de referencia para comparar
norma =  2.054524793679143
xmine =

 Columns 1 through 3:

  -5.707221358904505e-01  -6.818069531931934e-01  -7.022100790469721e-01

 Columns 4 through 6:

  -7.055106342822092e-01  -7.049061639722159e-01  -7.014966240007136e-01

 Columns 7 through 9:

  -6.918893572905522e-01  -6.657965808413541e-01  -5.960352112260985e-01

 Column 10:

  -4.164123479439683e-01



`Método de Broyden`

In [40]:
xmine=Broyden(@Fe,@JFe,x0e,1e-4,100)

No hay punto óptimo de referencia para comparar
norma =  2.054525961023157
xmine =

 Columns 1 through 3:

  -5.707158988885547e-01  -6.818032636339446e-01  -7.022096010009772e-01

 Columns 4 through 6:

  -7.055123682427044e-01  -7.049092366220059e-01  -7.015001428914708e-01

 Columns 7 through 9:

  -6.918920774734860e-01  -6.657973007846727e-01  -5.960345351109219e-01

 Column 10:

  -4.164147325579162e-01



In [41]:
norm(Fe(xmine))

ans =    3.805485147653437e-05


En este último inciso, sorprendentemente, obtuvimos el mismo resultado para cada uno de los métodos dados. La norma de la función evaluada en el punto obtenido está calculada en la celda inmediatamente anterior.

$OP-P3-E3$ Primero debemos implementar el algoritmo de minimización irrestricta con búsqueda lineal y backtracking usando como dirección la obtenida por el método de Newton modificado. Lugeo procedremos a probar la implementación con algunos ejemplos.
Para ello, implementaremos antes algunos algotimos auxiliares, a saber:
- `choleskycomp`, que calcula el factor de Cholesky de una matriz simétrica y definida positiva;
- `backtracking`;
- `soltrinf`, implementado para resolver sistemas de ecuaciones lineales donde la matriz es triangular inferior; y
- `soltrsup`, implementado para resolver sistemas de ecuaciones lineales donde la matriz es triangular superior.


In [42]:
function L = choleskycomp(A)


n = size(A)(1);
N=(A');
if (not(prod(prod(A == N))))
    disp("La matriz no es simétrica");
end

for i = 1:n
    for k = 1:(i-1)
        A(i,i) = A(i,i) - A(k,i)^2;
    end
    if A(i,i) <= 0
        L=zeros(n,n);
        return;
    end
    A(i,i) = sqrt(A(i,i));
    for j = (i+1):n
        for k = 1:(i-1)
            A(i,j) = A(i,j) - A(k,i) * A(k,j);
        end
        A(i,j) = A(i,j) / A(i,i);
    end
end
L=triu(A);
end



In [43]:
function t= backtracking(F,JF, x, d, t, p=0.5, a=1e-4)
q= F(x);
g=JF(x);
while F(x + t*d) > q + a*t*(g'*d)
t = t*p;
end
end


In [44]:
function x = soltrinf(A, b)
  n = length(A);
    d = 1;
    for i = 1:n
        d = d * A(i,i);
    endfor
    if(d != 0.0)
        for i = 1:n
          x(i) = b(i);
        for j = 1:1:i-1
            x(i) = x(i)-x(j)*A(i,j);
             endfor
             x(i) = x(i)/A(i,i);
        endfor
    else
    printf("Error: la matriz es singular");
    endif
endfunction

In [45]:
function x = soltrsup(A, b)
  n = length(b);
    d = 1;
    for i = 1:n
        d = d * A(i,i);
    endfor
    if(d != 0.0)
        for i = n:-1:1
          x(i) = b(i);
        for j = n:-1:i+1
            x(i) = x(i)-x(j)*A(i,j);
      endfor
          x(i) = x(i)/A(i,i);
    endfor
    else
        printf("Error: la matriz es singular");
    endif
endfunction


Ahora que tenemos nuestras rutinas auxiliares, procedemos a implementar el algortimo `min_back` que calcula lo deseado:

In [46]:
function x0= min_back(F, JF, HF, a, b, o, x0, tol,iter)
g=JF(x0);
h=1;
n=length(x0);
y=zeros(n);
m=1;
je=1;
k=1;
Hf=HF(x0);
while(norm(g)>tol)
B=Hf;
E=Hf;
j=1;
e=1;
L = choleskycomp(Hf); #en este paso verificamos si HF es definida positiva, sino lo es sumamos m*Id hasta que lo sea
        while(L==zeros(n,n))
        B=HF(x0)+m*e*eye(n);
        Hf=B;
        e=e+1;
        L = choleskycomp(Hf);
        endwhile
        e=1;
        LT=L';
            z=soltrinf(LT,-g);
            y=soltrsup(L,z);
                while(g*y'>-o*norm(g)*norm(y)) #verificamos que cumpla condición del ángulo de no hacerlo volvemos al paso anterior
                m=10*k;
                I=m*eye(n);
                E=E+I;
                Hf=E;
                k=k+1;
                L = choleskycomp(Hf);
                 while(L==zeros(n,n))
                B=Hf(x0)+m*e*eye(n);
                Hf=B;
                e=e+1;
                L = choleskycomp(Hf);
                endwhile
                z=soltrinf(LT,-g);
                y=soltrsup(L,z);
                endwhile
                w1=norm(g);
                w2=norm(y);
                    if(w2<b*w1) #en este paso ajustamos la direccón y
                w=(w1/w2);
                y=w*y;
                endif
                x1=x0+h*y;
                x2=F(x0);
                x2=x2+a*h*g*y';
                a1=F(x1);
                a2=x2;
                while (a1>a2)
                h= backtracking(@F, @JF,x0, y, h, p=0.5, a=1e-4); #aplicamos backtraacking hasta que F(x0+h*y)<=F(x0)+a*h*g*y'
                j=j+1;
                x1=x0+h*y;
                x2=F(y);
                x2=x2+a*h*g*y';
                a1=F(x1);
                a2=x2;
                endwhile
                x0=x0+h*y; #actualizamos los datos
                g=JF(x0);
                Hf=HF(x0);
                B=Hf;
                E=Hf;
                m=1;
                #k=1;
                j=j+1;
                h=1;
                #je=je+1;
                e=1;
                endwhile
                
            
        end

Ahora sí, estamos en condiciones de probar nuestra implementación con los siguientes ejemplos. En cada uno procederemos a programar la función objetivo, su Jacobiana y su Hessiana. 

$(a)$ $f(x)=x_1^2+x_2^2+x_3^2$ con $x_0=(1,1,1)$

In [47]:
#Cargamos el vector inicial para correr nuestro algoritmo
x0_a=ones(1,3)

x0_a =

   1   1   1



In [48]:
function F=F(x)
F=norm(x)^2;
end

In [49]:
function JF=JF(x)
JF=[2*x(1) 2*x(2) 2*x(3)];
end

In [50]:
function HF=HF(x)
HF=2*eye(3);
end

In [51]:
x_min_a= min_back(@F, @JF, @HF, 1e-4, 4, 1e-6, x0_a, 1,100)

x_min_a =

   0   0   0



El resultado obtenido es el vector nulo, que sabemos que es el único cuya norma es cero. Por lo tanto, podemos afirmar que nuestra solución obtenida con `min_back`es exacta

$(b)$ $f(x)=(x_1+x_2)^4+x_2^2$ con $x_0=(-2,2)$

In [52]:
#Cargamos el vector inicial para correr nuestro algoritmo
x0_b=[-2 2]

x0_b =

  -2   2



In [53]:
function F=F(x)
F=(x(1)+x(2))^4+x(2)^2;
end

In [54]:
function JF=JF(x)
JF=[4*((x(1)+x(2)))^3 4*((x(1)+x(2)))^3+2*x(2)];
end

In [55]:
function HF=HF(x)
HF=[12*(x(1)+x(2))^2 12*(x(1)+x(2))^2;12*(x(1)+x(2))^2 12*(x(1)+x(2))^2+2];
end

In [56]:
x_min_b= min_back(@F, @JF,@HF, 1e-4, 4, 1e-6, x0_b, 1e-4,50)

x_min_b =

  -3.275335648990002e-05  -3.101211373546269e-05



In [57]:
F(x_min_b)

ans =    9.617512148739160e-10


Aquí vemos que nuestra solución es un vector cuyas componenes son muy pequeñas y aproximan a cero en cada componente, lo que es correcto ya que el mínimo de esta función está en el punto $x=(0,0)$ y en el mismo vale $F(x)=0$

$(c)$ $f(x)=1000(x_2-x_1^2)^2+x_2^2$ con $x_0=(-1.2,1)$

In [58]:
#Cargamos el vector inicial para correr nuestro algoritmo
x0_c=[-1.2 1]

x0_c =

  -1.200000000000000   1.000000000000000



In [59]:
function F=F(x)
F=100*((x(2)-x(1)^2))^2+x(2)^2;
end

In [60]:
function JF=JF(x)
JF=[-400*(x(2)-x(1)^2)*x(1) 200*(x(2)-x(1)^2)+2*x(2)];
end

In [61]:
function HF=HF(x)
HF=[1200*x(1)^2-400*x(2) -400*x(1); -400*x(1) 202];
end

In [62]:
x_min_c= min_back(@F, @JF,@HF, 1e-4, 4, 1e-6, [-1.2,1], 1e-4,1000)

x_min_c =

  -3.580905061297378e-03   1.231327554882966e-05



In [63]:
F(x_min_c)

ans =    1.775865322416488e-10


Aquí nuevamente nuestro algoritmo se acerca a la solución del problema que está en $x=(0,0)$, acercandose con una precisión menor a la pedida. 

$OP-P4-E3$ Considerar el problema

$$Minimizar ~ f(x) = x_1 + x_2$$
$$sujeto ~ a ~ x_1 \geq 0$$
$$x_2 \geq 0$$
$$ x_1 + x_2\leq 1$$

Supongamos que se usa la función barrera logarítmica para resolverlo.

$a)$ Calcular $x(\mu)$, $\lambda(\mu)$ y $x_*$, $\lambda_*$.\
En primer lugar observemos que la tercera restricción, $ x_1 + x_2\leq 1$, es equivalente a $1-(x_1 + x_2)\geq 0$ y así llamamos:\
$$g_1(x)=x_1,$$\
$$g_2(x)=x_2,$$ y\
$$g_3(x)=x_1 + x_2$$\
Donde $g_i(x)\leq 0  ~\forall  ~ i  \in ~1:3$\
Ahora, la barrera *logarítmica* es $\phi(x)=-\sum_{ i  \in ~1:3} log(g_i(x))$, y así obetenemos la *función barrera*\
$$\beta_{\mu}(x)=f(x)-\mu \sum_{ i  \in ~1:3} log(g_i(x))=x_1 + x_2-\mu log(x_1)-\mu log(x_2) -\mu log(1-(x_1+x_2))$$
Para $\mu$ fijo, las condiciones de optimalidad son:\
$$\Bigg\{\begin{matrix}
            1 - \frac{\mu}{x_1}+ \frac{\mu}{1-(x_1+x_2)} = 0\\
            1 - \frac{\mu}{x_2}+ \frac{\mu}{1-(x_1+x_2)} = 0
            \end{matrix}$$\
Luego,\
$$1 - \frac{\mu}{x_1}+ \frac{\mu}{1-(x_1+x_2)}=1 - \frac{\mu}{x_2}+ \frac{\mu}{1-(x_1+x_2)}$$ de donde,\
$$\frac{\mu}{x_1}=\frac{\mu}{x_2} \Leftrightarrow ~ x_1=x_2 ~ (*)$$ Reemplazando en las condiciones de optimalidad, \
$$1 - \frac{\mu}{x_1}+ \frac{\mu}{1-2x_1)}=0$$ buscando denominador común\
$$ \frac{x_1(1-2x_1)-\mu(1-2x_1)+\mu x_1}{x_1(1-2x_1)}=0$$ si las restricciones son estrictas,\
$$x_1(1-2x_1)-\mu(1-2x_1)+\mu x_1=0$$ es decir,\
$$-2 x_1^2+(3\mu +1)x_1-\mu=0$$ y tenemos\
$$x_1(\mu)=\frac{-(3\mu +1)\pm\sqrt{(3\mu +1)^2-8\mu}}{-4}=\frac{(3\mu +1)\mp\sqrt{(3\mu +1)^2-8\mu}}{4}$$ nos quedamos con\
$$x_1(\mu)=\frac{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}{4} ~ (**)$$ y así\
$$x_{1,*}=\lim_{\mu\rightarrow 0} \frac{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}{4}= \frac{(3(0) +1)-\sqrt{(3(0) +1)^2-8(0)}}{4}=\frac{1-\sqrt{1^2}}{4}=0$$ como habíamos establecido en $(*)$, $x_{2,*}=x_{1,*}$ y así\
$$x_*=(0,0)$$
También de $(*)$ se desprende que $x_1+x_2=2x_1$ de donde $0\leq 2x_1\leq 1$ y de allí podemos concluir que el mínimo de $2x_1$ en esas restricciones se da cuando $x_1=0$ y así también podemos establecer el valor para $x_*$ sin necesidad de tomar límite cuando $\mu\rightarrow 0$\
Pasamos a calcular $\lambda(\mu)$. Hemos visto que:
$$\lambda_i(\mu)=\frac{\mu}{g_i(x)}$$
Por lo cual\
$$\lambda_1(\mu)=\frac{\mu}{x_1(\mu)}=\frac{4\mu}{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}$$ por $(*)$,\
$$\lambda_2(\mu)=\frac{\mu}{x_2(\mu)}=\frac{4\mu}{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}$$ y finalmente\
$$\lambda_3(\mu)=\frac{\mu}{1-2x_1(\mu)}=\frac{\mu}{1-\frac{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}{2}}$$
Calculamos:
$$\lambda_{1,*}=\lim_{\mu\rightarrow 0}\lambda_1(\mu)=\lim_{\mu\rightarrow 0}\frac{\mu}{x_1(\mu)}=\lim_{\mu\rightarrow 0}\frac{4\mu}{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}=1$$ y también
$$\lambda_{2,*}=\lim_{\mu\rightarrow 0}\lambda_2(\mu)=\lim_{\mu\rightarrow 0}\frac{\mu}{x_2(\mu)}=\lim_{\mu\rightarrow 0}\frac{4\mu}{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}=1$$ por último
$$\lambda_{3,*}=\lim_{\mu\rightarrow 0}\lambda_3(\mu)=\lim_{\mu\rightarrow 0}\frac{\mu}{1-2x_1(\mu)}=\lim_{\mu\rightarrow 0}\frac{\mu}{1-\frac{(3\mu +1)-\sqrt{(3\mu +1)^2-8\mu}}{2}}=0$$ Lo cual establece que $\lambda_*=(1,1,0)$ \


$b)$ Calcular la matriz Hessiana de la función barrera logarítmica para $\mu = 10^{-4}$. Calcular la inversa de esta matriz.

La Hessiana de la función barrera logarítmica es:

$$D^2 \beta_{\mu}(x) =\begin{pmatrix}
                                \frac{\mu}{x_1^2}+ \frac{\mu}{(1-(x_1+x_2))^2} & \frac{\mu}{(1-(x_1+x_2))^2} \\
                                \frac{\mu}{(1-(x_1+x_2))^2} & \frac{\mu}{x_2^2}+ \frac{\mu}{(1-(x_1+x_2))^2}
                             \end{pmatrix}$$
Calculamos $x_1(10^{-4})=\frac{(3\cdot10^{-4} +1)-\sqrt{(310^{-4} +1)^2-8\cdot10^{-4}}}{4}= 0.250050001249875$
Así, por $(*)$\
      $$D^2 \beta_{10^{-4}}(x(10^{-4})) =\begin{pmatrix}
                                \frac{10^{-4}}{(0.250050001249875)^2}+ \frac{10^{-4}}{(1-2\cdot0.250050001249875))^2} & \frac{\mu}{(1-(2\cdot0.250050001249875))^2} \\
                                \frac{10^{-4}}{(1-(2\cdot0.250050001249875))^2} & \frac{10^{-4}}{(0.250050001249875)^2}+ \frac{10^{-4}}{(1-2\cdot0.250050001249875))^2}
                             \end{pmatrix}$$
Como calculamos en las celdas siguientes, nos queda:\
 $$D^2 \beta_{10^{-4}}(x(10^{-4})) =\begin{pmatrix}
                                1.999520239961616\cdot 10^{-3} &  4.001600480128032\cdot 10^{-4} \\
                                4.001600480128032\cdot 10^{-4} & 1.999520239961616\cdot 10^{-3}
                             \end{pmatrix}$$
Cuya inversa es:\
 $$[D^2 \beta_{10^{-4}}(x(10^{-4}))]^{-1} =\begin{pmatrix}
                                 520.9861023108649 &  -104.2639226891352 \\
                                -104.2639226891352 &  520.9861023108649
                             \end{pmatrix}$$

In [64]:
mu=1e-4
x_1=(3*mu+sqrt(1-2*mu+mu^2))/4

mu =    1.000000000000000e-04
x_1 =    2.500500000000000e-01


In [65]:
D=[(mu/((x_1)^2))+(mu/((1-2*x_1)^2)) (mu/((1-2*x_1)^2));(mu/((1-2*x_1)^2))  (mu/((x_1)^2))+(mu/((1-2*x_1)^2))]

D =

   1.999520239961616e-03   4.001600480128032e-04
   4.001600480128032e-04   1.999520239961616e-03



In [66]:
inv(D)

ans =

   520.9861023108649  -104.2639226891352
  -104.2639226891352   520.9861023108649

